/**
 * AOCN Data Layer
 * Provides card data from Renaiss marketplace via server API
 * Also includes static data for SBT, events, gacha, and ecosystem stats
 * SBT data sourced from official Google Doc: https://docs.google.com/document/d/1Tch9-CuDa4co2zT6sak318cuJiHHCAXek6SVDrLuShY
 */

// ─── Card Type ───
export interface Card {
  id: string;
  itemId: string;
  tokenId: string;
  name: string;
  setName: string;
  set: string;
  price: number;
  fmv: number;
  buyback: number;
  spread: number;
  spreadPct: number;
  imgUrl: string;
  grade: string;
  gradingCompany: string;
  year: number;
  language: string;
  cardNumber: string;
  serial: string;
  vaultLocation: string;
  ownerUsername: string;
  ebaySearchUrl: string;
}

// ─── Ecosystem Stats (Official: 210K+ users, $3.4M+ volume, verified 2026-03) ───
export const ecosystemStats = {
  totalUsers: 250000,
  totalVolume: 4200000,
  totalCards: 3880,
  holders: 4200,
};

// ─── Timeline Events ───
export interface TimelineEvent {
  id: string;
  date: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  source: string;
  sourceUrl: string;
  hasSbt: boolean;
  type: string;
  sourceType?: string;
  sbtInfo?: string;
  sbtInfoEn?: string;
}

// Verified events from @renaissxyz Twitter, Binance, GlobeNewsWire, BNB Chain blog
// Last verified: 2026-03-12
export const timelineEvents: TimelineEvent[] = [
  {
    id: 'evt-amb2',
    date: '2026-03-12',
    title: 'Renaiss Ambassador 2.0 区域大使候选名单公布',
    titleEn: 'Renaiss Ambassador 2.0 Regional Candidate List Released',
    description: '来自韩国、马来西亚等不同地区的贡献者候选名单公布，社区投票将于 3月13-16日在 Discord 进行，由社区决定下一任区域大使。',
    descriptionEn: 'Candidate lists from Korea, Malaysia and other regions published. Community voting on Discord from Mar 13-16 to decide next Regional Ambassadors.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: false,
    type: 'twitter',
  },
  {
    id: 'evt-korea-redemption',
    date: '2026-03-11',
    title: 'Renaiss Korea Alpha Redemption 首尔线下兑换活动',
    titleEn: 'Renaiss Korea Alpha Redemption - Seoul Offline Event',
    description: 'Renaiss 将前往首尔举办特别线下兑换活动，韩国用户可兑换实体卡片并参加社区聚会。',
    descriptionEn: 'Renaiss visiting Seoul for a special offline redemption event. Korean users can redeem physical cards and join a community meetup.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: false,
    type: 'twitter',
  },
  {
    id: 'evt-dual-machine',
    date: '2026-03-06',
    title: 'Renacrypt & Omega Pack 双卡机上线',
    titleEn: 'Renacrypt & Omega Pack Dual Card Machine Launch',
    description: 'Renacrypt Pack（Renaiss × Collector Crypt 联名）和 OMEGA Pack 同时上线，为无限卡池模式。上线时间延迟至 6PM (UTC+8)。',
    descriptionEn: 'Renacrypt Pack (Renaiss × Collector Crypt collab) and OMEGA Pack launched simultaneously as infinite gacha pools. Launch delayed to 6PM (UTC+8).',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz/status/2029119526445695063',
    hasSbt: false,
    type: 'twitter',
  },
  {
    id: 'evt-voyaga',
    date: '2026-02-27',
    title: 'Voyaga Pack (One Piece) & 宝可梦30周年双 IP 卡包上线',
    titleEn: 'Voyaga Pack (One Piece) & Pokémon 30th Anniversary Dual IP Launch',
    description: 'Renaiss 首次推出 One Piece 主题卡包 Voyaga Pack（限量400张，$85/抽），同时发布宝可梦30周年纪念卡包。两个卡包均快速售罄。',
    descriptionEn: 'First-ever One Piece pack "Voyaga Pack" (400 cards, $85/pull) launched alongside Pokémon 30th anniversary packs. Both sold out rapidly.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz/status/2027036031862894930',
    hasSbt: false,
    type: 'twitter',
  },
  {
    id: 'evt-pack4',
    date: '2026-02-20',
    title: 'Pack 4.0 上线 & 回购钱包事件',
    titleEn: 'Pack 4.0 Launch & Buyback Wallet Event',
    description: 'Legacy Pack 4.0 上线后回购钱包耗尽，成为 Renaiss 最混乱的时刻之一。The Survivor SBT 颁发给在此期间活跃的用户。',
    descriptionEn: 'Legacy Pack 4.0 launched and buyback wallet was depleted, becoming one of the most chaotic moments in Renaiss. The Survivor SBT was awarded to active users.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'The Survivor SBT',
    sbtInfoEn: 'The Survivor SBT',
  },
  {
    id: 'evt-bnb-lunar',
    date: '2026-02-17',
    title: 'BNB X Renaiss Lunar New Year 2026 活动',
    titleEn: 'BNB X Renaiss Lunar New Year 2026 Campaign',
    description: 'BNB Chain 与 Renaiss 联合举办农历新年活动，总奖池 $11,000，100位获奖者。包含 Fortune Trading & Gacha 活动。',
    descriptionEn: 'BNB Chain and Renaiss co-hosted Lunar New Year campaign with $11,000 total prize pool, 100 winners. Includes Fortune Trading & Gacha activities.',
    source: 'BNB Chain / DappBay',
    sourceUrl: 'https://dappbay.bnbchain.org/campaign/435-renaiss-lunar-new-year-gala-fortune-trading-gacha',
    hasSbt: false,
    type: 'twitter',
  },
  {
    id: 'evt-consensus-hk-2026',
    date: '2026-02-16',
    title: 'Renaiss 在 Consensus Hong Kong 2026 展示 $15M+ 实体收藏品',
    titleEn: 'Renaiss Showcases $15M+ Physical Collectibles at Consensus HK 2026',
    description: 'Renaiss 在 Consensus Hong Kong 2026 展示了价值超过 $15M 的实体收藏品，展示其在 BNB Chain 上的基础设施。',
    descriptionEn: 'Renaiss showcased $15M+ physical collectibles at Consensus Hong Kong 2026, demonstrating infrastructure on BNB Chain.',
    source: 'GlobeNewsWire',
    sourceUrl: 'https://www.globenewswire.com/news-release/2026/02/16/3238781/0/en/Renaiss-Showcases-15M-Physical-Collectibles-at-Consensus-Demonstrating-Infrastructure-on-BNB-Chain.html',
    hasSbt: false,
    type: 'news',
  },
  {
    id: 'evt-2026packs',
    date: '2026-02-01',
    title: '2026 年卡包上线',
    titleEn: '2026 Card Packs Launch',
    description: '2026 年新卡包正式上线，Heat Survivor 和 New Year Opener SBT 颁发给早期参与者。',
    descriptionEn: '2026 card packs officially launched. Heat Survivor and New Year Opener SBTs awarded to early participants.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Heat Survivor & New Year Opener SBT',
    sbtInfoEn: 'Heat Survivor & New Year Opener SBT',
  },
  {
    id: 'evt-yearaward',
    date: '2026-01-15',
    title: '2025 年终颁奖典礼',
    titleEn: '2025 Year-End Awards Ceremony',
    description: 'Renaiss 举办 2025 年终颁奖典礼，颁发 Hall of Fame、Conviction Holder、Signal Amplifier 等多个年度奖项 SBT。',
    descriptionEn: 'Renaiss hosted the 2025 Year-End Awards Ceremony, awarding multiple annual SBTs including Hall of Fame, Conviction Holder, Signal Amplifier and more.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: '多个 2025 Year Award SBT',
    sbtInfoEn: 'Multiple 2025 Year Award SBTs',
  },
  {
    id: 'evt-frozen',
    date: '2025-12-29',
    title: 'Frozen Pack 年末限定卡包',
    titleEn: 'Frozen Pack Year-End Limited Edition',
    description: 'Renaiss 推出年末限定 Frozen Pack，2000个卡包在 11 分钟内售罄。',
    descriptionEn: 'Renaiss launched year-end limited Frozen Pack. 2000 packs sold out in 11 minutes.',
    source: 'WEEX News',
    sourceUrl: 'https://www.weex.com/news/detail/renaiss-surpasses-1-million-in-total-trading-volume-one-month-after-launch-end-of-year-finale-card-pack-sold-out-in-11-minutes-292651',
    hasSbt: false,
    type: 'news',
  },
  {
    id: 'evt-christmas',
    date: '2025-12-25',
    title: '圣诞节社区活动',
    titleEn: 'Christmas Community Event',
    description: 'Renaiss 圣诞节社区活动，Christmas Carol SBT 颁发给积极参与的社区成员。',
    descriptionEn: 'Renaiss Christmas community event. Christmas Carol SBT awarded to active community members.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Christmas Carol SBT',
    sbtInfoEn: 'Christmas Carol SBT',
  },
  {
    id: 'evt-trading-arena',
    date: '2025-12-20',
    title: 'Renaiss Trading Arena 第一赛季',
    titleEn: 'Renaiss Trading Arena Season 1',
    description: '首届 Renaiss 交易锦标赛举办，Top Trader SBT 颁发给排名前十的交易员。',
    descriptionEn: 'First Renaiss Trading Arena competition held. Top Trader SBT awarded to top 10 traders.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Top Trader SBT - Season 1',
    sbtInfoEn: 'Top Trader SBT - Season 1',
  },
  {
    id: 'evt-openbeta',
    date: '2025-12-19',
    title: 'Renaiss Protocol Open Beta 正式上线',
    titleEn: 'Renaiss Protocol Open Beta Launch',
    description: 'Renaiss Protocol Open Beta 正式上线，标志着项目进入新篇章。“It is Renaiss szn.”',
    descriptionEn: 'Renaiss Protocol Open Beta officially launched, marking a new chapter for the project. "It is Renaiss szn."',
    source: 'Renaiss Official / LinkedIn',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: false,
    type: 'twitter',
  },
  {
    id: 'evt-sprint',
    date: '2025-12-01',
    title: 'Sprint 限时套餐活动',
    titleEn: 'Sprint Limited-Time Pack Event',
    description: '限时 Sprint 套餐活动上线，Sprint Challenger SBT 颁发给参与者。',
    descriptionEn: 'Limited-time Sprint pack event launched. Sprint Challenger SBT awarded to participants.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Sprint Challenger SBT',
    sbtInfoEn: 'Sprint Challenger SBT',
  },
  {
    id: 'evt-closedbeta',
    date: '2025-11-14',
    title: 'Renaiss Protocol Closed Beta 上线',
    titleEn: 'Renaiss Protocol Closed Beta Launch',
    description: 'BNB Chain 上首个 TCG 平台 Renaiss Protocol 启动 Closed Beta，盲盒卡包在上线三小时内售罄。',
    descriptionEn: 'First TCG platform on BNB Chain, Renaiss Protocol, launched Closed Beta. Blind box card packs sold out within three hours.',
    source: 'Binance Square / Bitget',
    sourceUrl: 'https://www.binance.com/en/square/post/32372136592665',
    hasSbt: true,
    type: 'news',
    sbtInfo: 'Beta Pioneer & Early Bird SBT',
    sbtInfoEn: 'Beta Pioneer & Early Bird SBT',
  },
  {
    id: 'evt-legacy3',
    date: '2025-10-01',
    title: 'Legacy Pack 3.0 上线',
    titleEn: 'Legacy Pack 3.0 Launch',
    description: 'Legacy Pack 3.0 正式上线，Legacy Flash Mint 和 Legacy Triple Pull SBT 颁发给早期参与者。',
    descriptionEn: 'Legacy Pack 3.0 officially launched. Legacy Flash Mint and Legacy Triple Pull SBTs awarded to early participants.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Legacy Flash Mint & Legacy Triple Pull SBT',
    sbtInfoEn: 'Legacy Flash Mint & Legacy Triple Pull SBT',
  },
  {
    id: 'evt-ugc',
    date: '2025-09-15',
    title: 'Identity Flexer UGC 活动',
    titleEn: 'Identity Flexer UGC Campaign',
    description: '用户生成内容 (UGC) 活动启动，鼓励用户展示 renaiss.xyz 个人资料。Identity Flexer SBT 颁发。',
    descriptionEn: 'User Generated Content (UGC) campaign launched, encouraging users to showcase renaiss.xyz profiles. Identity Flexer SBT awarded.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Identity Flexer SBT',
    sbtInfoEn: 'Identity Flexer SBT',
  },
  {
    id: 'evt-infinite',
    date: '2025-08-01',
    title: '无限扭蛋 (Infinite Gacha) Beta 测试',
    titleEn: 'Infinite Gacha Beta Test',
    description: '无限扭蛋测试版上线，多个 SBT 颁发给参与者：Infinite Flash Mint、Infinite Grinder、Infinite Pioneer、Infinite Cursed、Infinite Flex。',
    descriptionEn: 'Infinite Gacha Beta launched. Multiple SBTs awarded: Infinite Flash Mint, Infinite Grinder, Infinite Pioneer, Infinite Cursed, Infinite Flex.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: '5个 Infinite 系列 SBT',
    sbtInfoEn: '5 Infinite series SBTs',
  },
  {
    id: 'evt-refs',
    date: '2025-07-15',
    title: 'Refs 生态系统 SBT 活动',
    titleEn: 'Refs Ecosystem SBT Event',
    description: 'Refs 生态系统 SBT 活动上线，Refs SBT 颁发给参与者。',
    descriptionEn: 'Refs ecosystem SBT event launched. Refs SBT awarded to participants.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Refs SBT',
    sbtInfoEn: 'Refs SBT',
  },
  {
    id: 'evt-newyear',
    date: '2025-02-01',
    title: '新年限定 SBT 活动',
    titleEn: 'New Year Limited SBT Event',
    description: '参与官推发布的活动，连续解锁5天 SBT 即可解锁隐藏财神爷 SBT。',
    descriptionEn: 'Participate in official events, unlock SBTs for 5 consecutive days to unlock the hidden God of Fortune SBT.',
    source: 'Renaiss Official',
    sourceUrl: 'https://x.com/renaissxyz',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: '新年限定 SBT + 隐藏财神爷 SBT',
    sbtInfoEn: 'New Year Limited SBT + Hidden God of Fortune SBT',
  },
  {
    id: 'evt-hk',
    date: '2025-01-20',
    title: 'Consensus Hong Kong 活动',
    titleEn: 'Consensus Hong Kong Event',
    description: '在 Consensus Hong Kong 期间，Hong Kong Explorer SBT 颁发给与 Renaiss CEO 面对面交流的用户。',
    descriptionEn: 'During Consensus Hong Kong, Hong Kong Explorer SBT awarded to users who met the Renaiss CEO in person.',
    source: 'Renaiss Official',
    sourceUrl: 'https://luma.com/6nid21c4',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Hong Kong Explorer SBT',
    sbtInfoEn: 'Hong Kong Explorer SBT',
  },
  {
    id: 'evt-ama',
    date: '2025-01-26',
    title: 'Renaiss Discord AMA',
    titleEn: 'Renaiss Discord AMA',
    description: '在 Renaiss Discord 上举行 AMA 活动，Live Participant SBT 颁发给参加者。',
    descriptionEn: 'AMA event held on Renaiss Discord. Live Participant SBT awarded to attendees.',
    source: 'Renaiss Official',
    sourceUrl: 'https://discord.gg/renaiss',
    hasSbt: true,
    type: 'twitter',
    sbtInfo: 'Live Participant SBT',
    sbtInfoEn: 'Live Participant SBT',
  },
];

// ─── Gacha Packs ───
export interface GachaPack {
  id: string;
  name: string;
  price: number;
  ev: number;
  evPct: number;
  tiers: { tier: number; probability: number; avgValue: number }[];
}

// Official data from renaiss.xyz/gacha (verified 2026-03-12)
export const gachaPacks: GachaPack[] = [
  {
    id: 'omega',
    name: 'OMEGA Pack',
    price: 48,
    ev: 52.32,
    evPct: 9,
    tiers: [
      { tier: 1, probability: 78.82, avgValue: 40 },   // Tier C: $20-$60
      { tier: 2, probability: 16.09, avgValue: 65 },   // Tier B: $60-$100
      { tier: 3, probability: 4.85, avgValue: 120 },   // Tier A: $100-$250
      { tier: 4, probability: 0.24, avgValue: 500 },   // Tier S: $250-$1,100+
    ],
  },
  {
    id: 'renacrypt',
    name: 'RenaCrypt Pack',
    price: 88,
    ev: 95.24,
    evPct: 8.2,
    tiers: [
      { tier: 1, probability: 76.5, avgValue: 72 },    // Tier C
      { tier: 2, probability: 18.0, avgValue: 95 },    // Tier B
      { tier: 3, probability: 5.0, avgValue: 180 },    // Tier A
      { tier: 4, probability: 0.5, avgValue: 500 },    // Tier S
    ],
  },
];

// ─── SBT Data (Complete from Google Doc) ───
export interface SbtItem {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  howToGet: string;
  howToGetEn: string;
  category: string;
  rarity: string;
  available: boolean;
  holders: number;
  imgUrl: string;
  relatedEventId?: string;
  whyAwarded?: string;
  whyAwardedEn?: string;
  benefits?: string;
  benefitsEn?: string;
}

export interface SbtCatalogItem {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  category: string;
  available: boolean;
  status: '✅' | '❌' | '⭕';
  holders: number;
  availableLabel?: string;
  howToGet?: string;
  howToGetEn?: string;
}

export const sbtItems: SbtItem[] = [
  // ── Currently Available (✅) ──
  {
    id: 'sbt-discord-booster',
    name: 'Discord Server Booster',
    nameEn: 'Discord Server Booster',
    description: '此徽章授予通过提升服务器性能来支持 Renaiss Discord 的用户，表彰对社区基础设施和长期生态系统稳定性的直接贡献。',
    descriptionEn: 'This badge is awarded to users who support the Renaiss Discord by boosting server performance, recognizing direct contributions to community infrastructure and long-term ecosystem stability.',
    howToGet: '至少提升一次 Renaiss Discord 服务器的优先级',
    howToGetEn: 'Boost the Renaiss Discord server at least once',
    category: 'social',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-community-dev',
    name: 'Community Developer 社区开发者',
    nameEn: 'Community Developer',
    description: '此奖授予为 Renaiss 构建应用程序、工具或 AI 系统的开发者，表彰那些为 Renaiss 做出意义重大的技术贡献。',
    descriptionEn: 'Awarded to developers who build applications, tools, or AI systems for Renaiss, recognizing significant technical contributions verified by the Renaiss team.',
    howToGet: '开发并提交支持 Renaiss 的应用程序、工具或 AI 系统，并经 Renaiss 团队验证',
    howToGetEn: 'Develop and submit applications, tools, or AI systems supporting Renaiss, verified by the Renaiss team',
    category: 'special',
    rarity: 'Rare',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-community-voice',
    name: 'Community Voice 社区之声',
    nameEn: 'Community Voice',
    description: '奖励给在 X + Discord 上传播知识、创作内容并积极参与讨论的人。',
    descriptionEn: 'Rewarded to those who spread knowledge, create content, and actively participate in discussions on X + Discord.',
    howToGet: '加入 DC 一个月内发布8篇 Renaiss 相关的高质量推文，即可联系社区等级3',
    howToGetEn: 'Post 8 high-quality Renaiss-related tweets within one month of joining DC, then contact community level 3',
    category: 'social',
    rarity: 'Uncommon',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-s-breaker',
    name: 'S+ Breaker',
    nameEn: 'S+ Breaker',
    description: '此徽章颁发给在 Renaiss 平台成功抽取到顶级的 S 级卡牌的收藏家，标志着一次意义非凡的抽卡经历。',
    descriptionEn: 'Awarded to collectors who successfully pull a top-tier S-grade card on the Renaiss platform, marking an extraordinary gacha experience.',
    howToGet: '在 Renaiss 上从任何符合条件的卡包中至少抽取一张顶级或 S 级卡牌',
    howToGetEn: 'Pull at least one top-tier or S-grade card from any eligible pack on Renaiss',
    category: 'gacha',
    rarity: 'Rare',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-discord-linker',
    name: 'Discord Linker',
    nameEn: 'Discord Linker',
    description: '奖励给连接 Discord 账号的用户，从而实现更深入的社区参与。',
    descriptionEn: 'Rewarded to users who link their Discord account, enabling deeper community engagement.',
    howToGet: '链接 Discord 账号',
    howToGetEn: 'Link your Discord account',
    category: 'social',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-fund-account',
    name: 'Fund Your Account 为您的账户注资',
    nameEn: 'Fund Your Account',
    description: '奖励给首次充值并开始全面参与 Renaiss 生态系统的用户。',
    descriptionEn: 'Rewarded to users who make their first deposit and begin fully participating in the Renaiss ecosystem.',
    howToGet: '在过去 3 天内完成单笔 60USDT 或以上的存款',
    howToGetEn: 'Complete a single deposit of 60 USDT or more within the past 3 days',
    category: 'trading',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-pack-opener',
    name: 'Pack Opener',
    nameEn: 'Pack Opener',
    description: '奖励给持续参与开包、发现新卡牌并推动生态系统发展的用户。',
    descriptionEn: 'Rewarded to users who consistently participate in pack opening, discovering new cards and driving ecosystem growth.',
    howToGet: '执行 5 次包装开封',
    howToGetEn: 'Open 5 packs',
    category: 'gacha',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-signal-booster',
    name: 'Signal Booster 信号增强器',
    nameEn: 'Signal Booster',
    description: '此徽章授予那些评论有力地支持并强化了创始人声音的社区成员，表彰那些深思熟虑的参与。',
    descriptionEn: 'Awarded to community members whose comments powerfully support and amplify the founder\'s voice, recognizing thoughtful engagement.',
    howToGet: '积极与官网&创始人推文互动，发表杰出评论，有几率获得',
    howToGetEn: 'Actively engage with official & founder tweets, post outstanding comments for a chance to earn',
    category: 'social',
    rarity: 'Uncommon',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-recruiter',
    name: 'The Recruiter',
    nameEn: 'The Recruiter',
    description: '奖励给通过招募新玩家帮助扩大 Renaiss 社区的用户。',
    descriptionEn: 'Rewarded to users who help expand the Renaiss community by recruiting new players.',
    howToGet: '成功邀请 5 位或更多新用户',
    howToGetEn: 'Successfully invite 5 or more new users',
    category: 'social',
    rarity: 'Uncommon',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-trader',
    name: 'The Trader',
    nameEn: 'The Trader',
    description: '此奖项颁发给积极通过持续交易为市场流动性做出贡献的用户，帮助在 Renaiss 构建健康且充满活力的经济体系。',
    descriptionEn: 'Awarded to users who actively contribute to market liquidity through consistent trading, helping build a healthy and vibrant economy on Renaiss.',
    howToGet: '完成3笔或以上有效交易',
    howToGetEn: 'Complete 3 or more valid trades',
    category: 'trading',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-x-linker',
    name: 'X Linker X 连接器',
    nameEn: 'X Linker',
    description: '奖励给关联其 Twitter 帐户的用户，以便启用未来的声誉层级。',
    descriptionEn: 'Rewarded to users who link their Twitter account, enabling future reputation tiers.',
    howToGet: '链接推特账号',
    howToGetEn: 'Link your Twitter/X account',
    category: 'social',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },

  // ── Special (⭕) ──
  {
    id: 'sbt-vanguard',
    name: 'The Vanguard',
    nameEn: 'The Vanguard',
    description: '该奖项授予自 Renaiss 生态系统创立之初就对其产生深远影响的资深且具影响力的品牌大使，包括KOL、早期支持者和重要合作伙伴。',
    descriptionEn: 'Awarded to senior and influential brand ambassadors who have had a profound impact on the Renaiss ecosystem since its inception, including KOLs, early supporters, and key partners.',
    howToGet: '早期支持者表现出最高的影响力，加入 Renaiss 大使',
    howToGetEn: 'Early supporters demonstrating the highest influence, joining as Renaiss ambassadors',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 0,
    imgUrl: '',
    whyAwarded: '表彰自 Renaiss 创立之初就产生深远影响的品牌大使',
    whyAwardedEn: 'Recognizing brand ambassadors with profound impact since Renaiss inception',
    benefits: '大使专属权益和社区领导地位',
    benefitsEn: 'Ambassador exclusive benefits and community leadership status',
  },

  // ── Ended (❌) ──
  {
    id: 'sbt-newyear',
    name: '新年限定SBT',
    nameEn: 'New Year Limited SBT',
    description: '新年活动限定 SBT，连续解锁5天可获得隐藏财神爷 SBT。',
    descriptionEn: 'New Year event limited SBT. Unlock for 5 consecutive days to get the hidden God of Fortune SBT.',
    howToGet: '参与官推发布的活动，连续解锁5天sbt即可解锁隐藏财神爷sbt',
    howToGetEn: 'Participate in official events, unlock SBTs for 5 consecutive days to unlock hidden God of Fortune SBT',
    category: 'event',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-newyear',
  },
  {
    id: 'sbt-hk-explorer',
    name: 'Hong Kong Explorer SBT',
    nameEn: 'Hong Kong Explorer SBT',
    description: '在 Consensus Hong Kong 期间捕捉到 Renaiss CEO 的用户获得。',
    descriptionEn: 'Awarded to users who met the Renaiss CEO during Consensus Hong Kong.',
    howToGet: '在 Consensus Hong Kong 期间捕捉到 Renaiss CEO',
    howToGetEn: 'Meet the Renaiss CEO during Consensus Hong Kong',
    category: 'event',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-hk',
  },
  {
    id: 'sbt-infinite-flash',
    name: 'Infinite Flash Mint 无限闪光薄荷',
    nameEn: 'Infinite Flash Mint',
    description: '此徽章颁发给在无限扭蛋 Beta 测试上线后 15 分钟内进入游戏的用户，标志着 Beta 测试期间的早期参与。',
    descriptionEn: 'Awarded to users who entered the game within 15 minutes of the Infinite Gacha Beta launch, marking early participation during Beta testing.',
    howToGet: '在无限扭蛋测试上线后的前 15 分钟内购买礼包',
    howToGetEn: 'Purchase a pack within the first 15 minutes of the Infinite Gacha Beta launch',
    category: 'gacha',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-infinite',
  },
  {
    id: 'sbt-infinite-grinder',
    name: 'Infinite Grinder 无限研磨机',
    nameEn: 'Infinite Grinder',
    description: '此徽章颁发给积极参与无限扭蛋测试版并多次开启卡包的用户，彰显用户在测试阶段的持续参与。',
    descriptionEn: 'Awarded to users who actively participated in the Infinite Gacha Beta and opened multiple packs, highlighting sustained engagement during testing.',
    howToGet: '在无限扭蛋测试期间开启至少 5 个或更多礼包',
    howToGetEn: 'Open at least 5 or more packs during the Infinite Gacha Beta test',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-infinite',
  },
  {
    id: 'sbt-infinite-pioneer',
    name: 'Infinite Pioneer 无限先锋',
    nameEn: 'Infinite Pioneer',
    description: '奖励给参与无限扭蛋测试版并开启首个卡包的用户，标志着提前体验无限扭蛋。',
    descriptionEn: 'Rewarded to users who participated in the Infinite Gacha Beta and opened their first pack, marking early access to the Infinite Gacha.',
    howToGet: '在无限扭蛋测试期间至少打开 1 个卡包',
    howToGetEn: 'Open at least 1 pack during the Infinite Gacha Beta test',
    category: 'gacha',
    rarity: 'Common',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-infinite',
  },
  {
    id: 'sbt-legacy-flash',
    name: 'Legacy Flash Mint 传承闪卡',
    nameEn: 'Legacy Flash Mint',
    description: '此徽章授予在 Legacy Pack 3.0 上线后一分钟内进入游戏的用户，标志着 Beta 测试版发布期间的早期参与。',
    descriptionEn: 'Awarded to users who entered the game within one minute of Legacy Pack 3.0 launch, marking early participation during Beta release.',
    howToGet: '在 Legacy 3.0 礼包上线后的第一分钟内购买礼包',
    howToGetEn: 'Purchase a pack within the first minute of Legacy 3.0 pack launch',
    category: 'gacha',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-legacy3',
  },
  {
    id: 'sbt-legacy-triple',
    name: 'Legacy Triple Pull 传承三拉',
    nameEn: 'Legacy Triple Pull',
    description: '奖励给在活动期间成功完成三次合格抽奖的用户。',
    descriptionEn: 'Rewarded to users who successfully completed three qualifying draws during the event.',
    howToGet: '在传承卡包 3.0 中打开 3 个卡包',
    howToGetEn: 'Open 3 packs in Legacy Pack 3.0',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-legacy3',
  },
  {
    id: 'sbt-live-participant',
    name: 'Live Participant 在线参与者',
    nameEn: 'Live Participant',
    description: '授予参加 1 月 26 日 Renaiss Discord AMA 的用户，记录了用户在现场的积极参与。',
    descriptionEn: 'Awarded to users who attended the January 26 Renaiss Discord AMA, recording active live participation.',
    howToGet: '参加 1 月 26 日在 Renaiss Discord 上举行的 AMA 活动',
    howToGetEn: 'Attend the AMA event held on Renaiss Discord on January 26',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-ama',
  },
  {
    id: 'sbt-infinite-cursed',
    name: 'Infinite Cursed 无尽的诅咒',
    nameEn: 'Infinite Cursed',
    description: '此徽章颁发给无限扭蛋测试版期间净亏损最高的5位用户，表彰在充满挑战的环境下所展现出的韧性和积极参与。',
    descriptionEn: 'Awarded to the top 5 users with the highest net loss during the Infinite Gacha Beta, recognizing resilience and active participation in challenging conditions.',
    howToGet: '在无限扭蛋测试版中净亏排名前5',
    howToGetEn: 'Rank in the top 5 for net loss during the Infinite Gacha Beta',
    category: 'gacha',
    rarity: 'Legendary',
    available: false,
    holders: 5,
    imgUrl: '',
    relatedEventId: 'evt-infinite',
  },
  {
    id: 'sbt-infinite-flex',
    name: 'Infinite Flex 无限弹性',
    nameEn: 'Infinite Flex',
    description: '此徽章颁发给在无限扭蛋测试版期间抽到 S 级卡牌并公开展示的用户。',
    descriptionEn: 'Awarded to users who pulled an S-grade card during the Infinite Gacha Beta and publicly showcased it.',
    howToGet: '无限扭蛋测试期间抽取一张 S 级卡牌，并按照官方活动指南在 X 上分享',
    howToGetEn: 'Pull an S-grade card during the Infinite Gacha Beta and share on X following official guidelines',
    category: 'gacha',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-infinite',
  },
  {
    id: 'sbt-refs',
    name: 'Refs SBT',
    nameEn: 'Refs SBT',
    description: '生态系统 SBT，活动已于2月5日下午4:00结束。',
    descriptionEn: 'Ecosystem SBT, event ended on February 5th at 4:00 PM.',
    howToGet: '用已绑定 Renaiss 的 X 账号注册 Refs 并关注 @whatsyourrefs',
    howToGetEn: 'Register on Refs with your Renaiss-linked X account and follow @whatsyourrefs',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-refs',
  },
  {
    id: 'sbt-early-bird',
    name: 'Early Bird',
    nameEn: 'Early Bird',
    description: '授予在 Alpha 阶段加入 Renaiss 的最早一批探险家。',
    descriptionEn: 'Awarded to the earliest explorers who joined Renaiss during the Alpha phase.',
    howToGet: '在 Alpha 测试期间至少登录一次',
    howToGetEn: 'Log in at least once during the Alpha testing period',
    category: 'community',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-beta',
  },
  {
    id: 'sbt-grand-ripper',
    name: 'Grand Ripper',
    nameEn: 'Grand Ripper',
    description: '授予那些在拆封方面表现出最高热情的用户——他们的热情几乎超过了生态系统中的其他所有人。',
    descriptionEn: 'Awarded to users who demonstrate the highest enthusiasm for pack opening — their passion surpasses nearly everyone else in the ecosystem.',
    howToGet: '完成200次或以上的包装开箱',
    howToGetEn: 'Complete 200 or more pack openings',
    category: 'gacha',
    rarity: 'Legendary',
    available: false,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-beta-pioneer',
    name: 'Beta Pioneer',
    nameEn: 'Beta Pioneer',
    description: '奖励给在 Renaiss 封测/测试期间登录一次并支持我们的用户。',
    descriptionEn: 'Rewarded to users who logged in once during the Renaiss closed/beta testing period and supported us.',
    howToGet: '在封闭/测试期间登录一次即可',
    howToGetEn: 'Log in once during the closed/beta testing period',
    category: 'community',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-beta',
  },
  {
    id: 'sbt-christmas-carol',
    name: 'Christmas Carol',
    nameEn: 'Christmas Carol',
    description: '此徽章颁发给积极参与圣诞节活动、分享 Renaiss 节日内容的社区成员。',
    descriptionEn: 'Awarded to community members who actively participated in Christmas events and shared Renaiss holiday content.',
    howToGet: '在圣诞节促销活动期间，至少发布一篇与 Renaiss 相关的圣诞节博文',
    howToGetEn: 'Post at least one Renaiss-related Christmas blog post during the Christmas promotion period',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-christmas',
  },
  {
    id: 'sbt-heat-survivor',
    name: 'Heat Survivor',
    nameEn: 'Heat Survivor',
    description: '此徽章颁发给在 2026 年产品高峰期参与的用户，记录了产品包发布期间的紧张时刻。',
    descriptionEn: 'Awarded to users who participated during the 2026 product peak period, recording the intense moments during pack releases.',
    howToGet: '在 2026 年包发上市期间，至少打开 1 包',
    howToGetEn: 'Open at least 1 pack during the 2026 pack launch period',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-2026packs',
  },
  {
    id: 'sbt-identity-flexer',
    name: 'Identity Flexer',
    nameEn: 'Identity Flexer',
    description: '此徽章授予通过经批准的用户生成内容 (UGC) 活动展示其 renaiss.xyz 个人资料的用户。',
    descriptionEn: 'Awarded to users who showcase their renaiss.xyz profile through approved User Generated Content (UGC) campaigns.',
    howToGet: '请按照官方规则参与"展示你的个人资料"用户生成内容 (UGC) 活动',
    howToGetEn: 'Participate in the "Show Your Profile" UGC campaign following official rules',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-ugc',
  },
  {
    id: 'sbt-ice-breaker',
    name: 'Ice Breaker',
    nameEn: 'Ice Breaker',
    description: '此徽章颁发给那些无惧严寒、坚持拆封冰冻包装的收藏家，标志着早期参与冰冻包装系列。',
    descriptionEn: 'Awarded to collectors who braved the cold and opened ice packs, marking early participation in the ice pack series.',
    howToGet: '打开5个或更多冷冻包装',
    howToGetEn: 'Open 5 or more ice packs',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-ice',
  },
  {
    id: 'sbt-new-year-opener',
    name: 'New Year Opener',
    nameEn: 'New Year Opener',
    description: '此徽章颁发给已开启 2026 卡包的用户，标志着在新的一年伊始的参与。',
    descriptionEn: 'Awarded to users who opened 2026 packs, marking participation at the start of the new year.',
    howToGet: '完成 5 次 2026 卡包的开启，或者在卡包上线后的前 20 小时内达成超过 100 美元的市场交易额',
    howToGetEn: 'Complete 5 openings of 2026 packs, or achieve over $100 in market trading volume within the first 20 hours of pack launch',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-2026packs',
  },
  {
    id: 'sbt-sprint-challenger',
    name: 'Sprint Challenger',
    nameEn: 'Sprint Challenger',
    description: '奖励给参与限时 Sprint 套餐活动并帮助促成售罄的用户。',
    descriptionEn: 'Rewarded to users who participated in the limited-time Sprint pack event and helped it sell out.',
    howToGet: '在 Sprint 活动期间或 Sprint 活动包售罄时，打开至少 1 个 Sprint 活动包',
    howToGetEn: 'Open at least 1 Sprint pack during the Sprint event or when the Sprint pack sells out',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-sprint',
  },
  {
    id: 'sbt-survivor',
    name: 'The Survivor',
    nameEn: 'The Survivor',
    description: '奖励给在 Pack 4.0 回购钱包耗尽期间活跃的用户——这是 Renaiss 中最混乱的时刻之一。',
    descriptionEn: 'Rewarded to users active during the Pack 4.0 buyback wallet depletion — one of the most chaotic moments in Renaiss.',
    howToGet: '在 Pack 4.0 期间打开至少 1 个卡包，或在公告发布前 24 小时内完成至少 1 笔交易',
    howToGetEn: 'Open at least 1 pack during Pack 4.0, or complete at least 1 trade within 24 hours before the announcement',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-pack4',
  },
  {
    id: 'sbt-debate-explorer',
    name: 'Debate Explorer',
    nameEn: 'Debate Explorer',
    description: '与 Renaiss 团队面对面交流的用户获得此徽章。',
    descriptionEn: 'Awarded to users who had face-to-face interactions with the Renaiss team.',
    howToGet: '与 Renaiss 团队本人见面',
    howToGetEn: 'Meet the Renaiss team in person',
    category: 'event',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-rng-martyr',
    name: 'RNG Martyr',
    nameEn: 'RNG Martyr',
    description: '颁发给开包净亏损最大的用户——象征着精疲力竭的随机数生成器和不屈不挠的精神。',
    descriptionEn: 'Awarded to users with the largest net loss from pack opening — symbolizing an exhausted RNG and indomitable spirit.',
    howToGet: '在特定时期内，包装开启造成的最大净损失',
    howToGetEn: 'Highest net loss from pack opening within a specific period',
    category: 'gacha',
    rarity: 'Legendary',
    available: false,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-supreme-collector',
    name: 'Supreme Collector',
    nameEn: 'Supreme Collector',
    description: '颁发给拥有卡片总数最多的收藏家，代表着无与伦比的拥有权和收藏实力。',
    descriptionEn: 'Awarded to the collector with the most total cards, representing unmatched ownership and collecting power.',
    howToGet: '持卡总量排名第一',
    howToGetEn: 'Rank #1 in total card holdings',
    category: 'trading',
    rarity: 'Legendary',
    available: false,
    holders: 1,
    imgUrl: '',
  },
  {
    id: 'sbt-top-trader-s1',
    name: 'Top Trader SBT - Season 1',
    nameEn: 'Top Trader SBT - Season 1',
    description: '此徽章授予首届 Renaiss 交易锦标赛中表现最佳的交易员，代表着卓越的交易技巧、稳定性以及竞争优势。',
    descriptionEn: 'Awarded to the best-performing traders in the first Renaiss Trading Arena competition, representing exceptional trading skills, stability, and competitive advantage.',
    howToGet: '在 Renaiss Trading Arena 第一赛季中排名前十',
    howToGetEn: 'Rank in the top 10 in Renaiss Trading Arena Season 1',
    category: 'trading',
    rarity: 'Legendary',
    available: false,
    holders: 10,
    imgUrl: '',
    relatedEventId: 'evt-trading-arena',
  },
  // 2025 Year Awards
  {
    id: 'sbt-hall-of-fame',
    name: '2025 Year Award — Hall of Fame',
    nameEn: '2025 Year Award — Hall of Fame',
    description: '此徽章颁发给在 Renaiss 年终颁奖典礼上获得官方赞誉的用户，代表全年杰出贡献。',
    descriptionEn: 'Awarded to users who received official recognition at the Renaiss Year-End Awards, representing outstanding contributions throughout the year.',
    howToGet: '在 Renaiss 年终颁奖典礼上赢得任何官方奖项',
    howToGetEn: 'Win any official award at the Renaiss Year-End Awards Ceremony',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-conviction-holder',
    name: '2025 Year Award — Conviction Holder',
    nameEn: '2025 Year Award — Conviction Holder',
    description: '此奖项颁发给卡片总价值最高的收藏家，表彰在市场周期中始终坚持的长期信念。',
    descriptionEn: 'Awarded to the collector with the highest total card value, recognizing long-term conviction through market cycles.',
    howToGet: '在2025年终评选期间，信用卡组合总价值排名前三',
    howToGetEn: 'Rank in the top 3 for total card portfolio value during the 2025 year-end selection',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 3,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-signal-amplifier',
    name: '2025 Year Award — Signal Amplifier',
    nameEn: '2025 Year Award — Signal Amplifier',
    description: '此奖项授予内容互动性和影响力最强的创作者，表彰推动时代发展的声音。',
    descriptionEn: 'Awarded to the creator with the strongest content engagement and influence, recognizing voices that drive the era forward.',
    howToGet: '在2025年终颁奖典礼期间，整体内容表现和互动度排名第一',
    howToGetEn: 'Rank #1 in overall content performance and engagement during the 2025 Year-End Awards',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 1,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-core-contributor',
    name: '2025 Year Award — Core Contributor',
    nameEn: '2025 Year Award — Core Contributor',
    description: '该奖项授予 Renaiss 2025 年最杰出的贡献者，代表着超越单一角色的持续影响力。',
    descriptionEn: 'Awarded to the most outstanding contributor to Renaiss in 2025, representing sustained impact beyond a single role.',
    howToGet: '入选 2025 年 Renaiss 年终奖的前三名贡献者',
    howToGetEn: 'Be selected as one of the top 3 contributors for the 2025 Renaiss Year-End Awards',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 3,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-growth-catalyst',
    name: '2025 Year Award — Growth Catalyst',
    nameEn: '2025 Year Award — Growth Catalyst',
    description: '该奖项授予在 2025 年推动 Renaiss 用户增长最活跃的顶级招募人员。',
    descriptionEn: 'Awarded to the top recruiters who most actively drove Renaiss user growth in 2025.',
    howToGet: '在2025年终颁奖典礼期间，受邀用户总数排名前三',
    howToGetEn: 'Rank in the top 3 for total invited users during the 2025 Year-End Awards',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 3,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-narrative-builder',
    name: '2025 Year Award — Narrative Builder',
    nameEn: '2025 Year Award — Narrative Builder',
    description: '授予在 2025 年持续创作高质量长篇内容的创作者。',
    descriptionEn: 'Awarded to creators who consistently produced high-quality long-form content in 2025.',
    howToGet: '在2025年终评选期间，长篇内容产量和质量排名前三',
    howToGetEn: 'Rank in the top 3 for long-form content volume and quality during the 2025 year-end selection',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 3,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-real-grinder',
    name: '2025 Year Award — Real Grinder',
    nameEn: '2025 Year Award — Real Grinder',
    description: '此奖项授予在 2025 年期间持续为 Renaiss 生态系统做出贡献的建设者。',
    descriptionEn: 'Awarded to builders who consistently contributed to the Renaiss ecosystem throughout 2025.',
    howToGet: '获取2025年文艺复兴年终奖"无声建设者奖"',
    howToGetEn: 'Win the 2025 Renaissance Year-End "Silent Builder Award"',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-referral-force',
    name: '2025 Year Award — Referral Force',
    nameEn: '2025 Year Award — Referral Force',
    description: '此徽章颁发给邀请用户促成最多礼包开启次数的用户。',
    descriptionEn: 'Awarded to users whose invited users generated the most pack openings.',
    howToGet: '在2025年终颁奖典礼期间，通过受邀用户开启的礼包总数排名前三',
    howToGetEn: 'Rank in the top 3 for total packs opened by invited users during the 2025 Year-End Awards',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 3,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-speed-of-hands',
    name: '2025 Year Award — Speed of Hands',
    nameEn: '2025 Year Award — Speed of Hands',
    description: '授予在 2025 年单独开启卡包数量最多的用户，象征着无与伦比的奉献精神。',
    descriptionEn: 'Awarded to the user who individually opened the most packs in 2025, symbolizing unmatched dedication.',
    howToGet: '在2025年终颁奖期间，个人开启的包装总数排名前三',
    howToGetEn: 'Rank in the top 3 for total packs opened individually during the 2025 Year-End Awards',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 3,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  {
    id: 'sbt-unluckiest',
    name: '2025 Year Award — The Unluckiest',
    nameEn: '2025 Year Award — The Unluckiest',
    description: '授予在 2025 年因 RNG 遭受最大净损失的用户。',
    descriptionEn: 'Awarded to the user who suffered the largest net loss due to RNG in 2025.',
    howToGet: '在2025年终评选期间，因RNG造成的最大净损失',
    howToGetEn: 'Highest net loss due to RNG during the 2025 year-end selection',
    category: 'special',
    rarity: 'Legendary',
    available: false,
    holders: 1,
    imgUrl: '',
    relatedEventId: 'evt-yearaward',
  },
  // ── New entries (补全至 69 个) ──
  {
    id: 'sbt-god-of-fortune',
    name: '财神爷',
    nameEn: 'God of Fortune',
    description: '完成新年活动连续5天解锁后获得的隐藏 SBT，新年活动的终极奖励。',
    descriptionEn: 'Hidden SBT unlocked after completing 5 consecutive days of the New Year event. The ultimate New Year reward.',
    howToGet: '连续完成新年 SBT 活动的全部5天',
    howToGetEn: 'Complete all 5 days of the New Year SBT event consecutively',
    category: 'event',
    rarity: 'Legendary',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-newyear',
  },
  {
    id: 'sbt-community-leader',
    name: '社区领袖',
    nameEn: 'Community Leader',
    description: '社区领袖角色的链上验证。SBT 持有者可以在官方 Renaiss 活动中代表其社区。',
    descriptionEn: 'On-chain verification of community leader role. SBT holders can represent their communities in official Renaiss initiatives.',
    howToGet: '通过社区领袖 SBT 计划申请并获得批准',
    howToGetEn: 'Apply through the Community Leader SBT Program and get approved',
    category: 'special',
    rarity: 'Rare',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-double-giant',
    name: '双巨人',
    nameEn: 'Double Giant',
    description: '通过在双卡机上线期间同时抽取 Renacrypt Pack 和 Omega Pack 解锁的专属 SBT。',
    descriptionEn: 'Exclusive SBT unlocked by drawing both Renacrypt Pack and Omega Pack during the dual card machine launch.',
    howToGet: '同时抽取 Renacrypt Pack 和 Omega Pack',
    howToGetEn: 'Draw both Renacrypt Pack and Omega Pack',
    category: 'gacha',
    rarity: 'Rare',
    available: true,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-dual-machine',
  },
  {
    id: 'sbt-ambassador',
    name: '大使 SBT',
    nameEn: 'Ambassador SBT',
    description: '授予参与 Renaiss Ambassador 2.0 计划的成员，该计划具有3级成长结构。',
    descriptionEn: 'Awarded to participants in the Renaiss Ambassador 2.0 Program with a 3-tier growth structure.',
    howToGet: '加入并被选入 Renaiss Ambassador 2.0 计划',
    howToGetEn: 'Join and be selected for the Renaiss Ambassador 2.0 Program',
    category: 'special',
    rarity: 'Rare',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-regional-ambassador',
    name: '区域大使',
    nameEn: 'Regional Ambassador',
    description: '通过社区投票选出的区域大使获得。每个区域选出两个角色：活跃大使和区域大使。',
    descriptionEn: 'Awarded to elected regional ambassadors through community voting. Each region elects two roles: Active Ambassador and Regional Ambassador.',
    howToGet: '在所在区域的社区投票中赢得区域大使选举',
    howToGetEn: 'Win the community vote for Regional Ambassador in your region',
    category: 'special',
    rarity: 'Legendary',
    available: true,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-amb2',
  },
  {
    id: 'sbt-voyaga-pioneer',
    name: 'Voyaga 先锋',
    nameEn: 'Voyaga Pioneer',
    description: '授予 Voyaga Pack（海贼王 IP）上线的早期参与者。Renaiss 上首批海贼王卡牌。',
    descriptionEn: 'Awarded to early participants of the Voyaga Pack (One Piece IP) launch. First-ever One Piece cards on Renaiss.',
    howToGet: '参与 Voyaga Pack 上线并至少开启 1 个卡包',
    howToGetEn: 'Participate in the Voyaga Pack launch and open at least 1 pack',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-voyaga',
  },
  {
    id: 'sbt-pokemon-30th',
    name: '宝可梦30周年纪念',
    nameEn: 'Pokémon 30th Anniversary',
    description: '纪念在 Renaiss 上参与宝可梦30周年纪念卡包上线的 SBT。',
    descriptionEn: 'Commemorative SBT for participants in the Pokémon 30th Anniversary card pack launch on Renaiss.',
    howToGet: '参与宝可梦30周年纪念卡包上线活动',
    howToGetEn: 'Participate in the Pokémon 30th Anniversary pack launch',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-voyaga',
  },
  {
    id: 'sbt-consensus-hk-2026',
    name: 'Consensus 香港 2026',
    nameEn: 'Consensus HK 2026',
    description: '授予在 Consensus Hong Kong 2026 上访问 Renaiss 展位的用户，展示了价值超过 $15M 的实体收藏品。',
    descriptionEn: 'Awarded to users who visited the Renaiss booth at Consensus Hong Kong 2026, where $15M+ in physical collectibles were showcased.',
    howToGet: '在 Consensus Hong Kong 2026 上访问 Renaiss 展位',
    howToGetEn: 'Visit the Renaiss booth at Consensus Hong Kong 2026',
    category: 'event',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-consensus-hk-2026',
  },
  {
    id: 'sbt-bnb-lunar-2026',
    name: 'BNB 农历新年 2026',
    nameEn: 'BNB Lunar New Year 2026',
    description: '授予参与 BNB Chain x Renaiss 农历新年 2026 活动的用户，总奖池 $17,000。',
    descriptionEn: 'Awarded to participants in the BNB Chain x Renaiss Lunar New Year 2026 campaign with $17,000 prize pool.',
    howToGet: '参与 BNB x Renaiss 农历新年活动',
    howToGetEn: 'Participate in the BNB x Renaiss Lunar New Year campaign activities',
    category: 'event',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-bnb-lunar',
  },
  {
    id: 'sbt-fortune-trading',
    name: '财运交易',
    nameEn: 'Fortune Trading',
    description: '在 BNB x Renaiss 农历新年 2026 活动期间参与 Fortune Trading 活动获得。',
    descriptionEn: 'Awarded for participating in the Fortune Trading activity during the BNB x Renaiss Lunar New Year 2026 event.',
    howToGet: '在农历新年活动期间完成 Fortune Trading 任务',
    howToGetEn: 'Complete Fortune Trading tasks during the Lunar New Year event',
    category: 'event',
    rarity: 'Common',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-bnb-lunar',
  },
  {
    id: 'sbt-fortune-gacha',
    name: '财运扭蛋',
    nameEn: 'Fortune Gacha',
    description: '在 BNB x Renaiss 农历新年 2026 活动期间参与 Fortune Gacha 活动获得。',
    descriptionEn: 'Awarded for participating in the Fortune Gacha activity during the BNB x Renaiss Lunar New Year 2026 event.',
    howToGet: '在农历新年活动期间完成 Fortune Gacha 任务',
    howToGetEn: 'Complete Fortune Gacha tasks during the Lunar New Year event',
    category: 'event',
    rarity: 'Common',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-bnb-lunar',
  },
  {
    id: 'sbt-korea-alpha-redemption',
    name: '韩国 Alpha 兑换',
    nameEn: 'Korea Alpha Redemption',
    description: '授予参与首尔线下兑换活动的韩国用户。',
    descriptionEn: 'Awarded to Korean users who participated in the Seoul offline redemption event.',
    howToGet: '参加在首尔举办的 Renaiss Korea Alpha Redemption 活动',
    howToGetEn: 'Attend the Renaiss Korea Alpha Redemption event in Seoul',
    category: 'event',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-korea-redemption',
  },
  {
    id: 'sbt-dual-machine-pioneer',
    name: '双卡机先锋',
    nameEn: 'Dual Machine Pioneer',
    description: '授予 2026年3月6日 Renacrypt 和 Omega Pack 双卡机上线的早期参与者。',
    descriptionEn: 'Awarded to early participants of the Renacrypt & Omega Pack dual card machine launch on March 6, 2026.',
    howToGet: '在双卡机上线后的第一小时内参与',
    howToGetEn: 'Participate in the dual card machine launch within the first hour',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-dual-machine',
  },
  {
    id: 'sbt-renacrypt-pioneer',
    name: 'Renacrypt 先锋',
    nameEn: 'Renacrypt Pioneer',
    description: '授予 Renacrypt Pack（Renaiss x Collector Crypt 联名）的早期参与者。',
    descriptionEn: 'Awarded to early participants of the Renacrypt Pack (Renaiss x Collector Crypt collaboration).',
    howToGet: '在上线期间至少开启 1 个 Renacrypt Pack',
    howToGetEn: 'Open at least 1 Renacrypt Pack during launch period',
    category: 'gacha',
    rarity: 'Uncommon',
    available: true,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-dual-machine',
  },
  {
    id: 'sbt-omega-pioneer',
    name: 'Omega 先锋',
    nameEn: 'Omega Pioneer',
    description: '授予 OMEGA Pack 的早期参与者，Renaiss 自研的永久扭蛋机。',
    descriptionEn: 'Awarded to early participants of the OMEGA Pack, Renaiss\' in-house perpetual gacha machine.',
    howToGet: '在上线期间至少开启 1 个 Omega Pack',
    howToGetEn: 'Open at least 1 Omega Pack during launch period',
    category: 'gacha',
    rarity: 'Uncommon',
    available: true,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-dual-machine',
  },
  {
    id: 'sbt-beta2-tester',
    name: 'Beta 2.0 测试者',
    nameEn: 'Beta 2.0 Tester',
    description: '授予参与 2026年3月6日启动的 Renaiss Beta 2.0 测试阶段的用户。',
    descriptionEn: 'Awarded to users who participated in the Renaiss Beta 2.0 testing phase launched on March 6, 2026.',
    howToGet: '参与 Beta 2.0 测试阶段',
    howToGetEn: 'Participate in the Beta 2.0 testing phase',
    category: 'community',
    rarity: 'Uncommon',
    available: true,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-dual-machine',
  },
  {
    id: 'sbt-first-trade',
    name: '首次交易',
    nameEn: 'First Trade',
    description: '授予在 Renaiss 市场上完成首次交易的用户。',
    descriptionEn: 'Awarded to users who complete their first trade on the Renaiss marketplace.',
    howToGet: '在 Renaiss 市场上完成首次交易',
    howToGetEn: 'Complete your first trade on the Renaiss marketplace',
    category: 'trading',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-frozen-pioneer',
    name: '冰冻先锋',
    nameEn: 'Frozen Pioneer',
    description: '授予年末限定 Frozen Pack 的早期参与者，该卡包在 11 分钟内售罄。',
    descriptionEn: 'Awarded to early participants of the Frozen Pack year-end limited edition that sold out in 11 minutes.',
    howToGet: '在年末限定销售期间购买 Frozen Pack',
    howToGetEn: 'Purchase a Frozen Pack during the year-end limited sale',
    category: 'gacha',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-frozen',
  },
  {
    id: 'sbt-pack4-pioneer',
    name: 'Pack 4.0 先锋',
    nameEn: 'Pack 4.0 Pioneer',
    description: '授予 Legacy Pack 4.0 上线的早期参与者。',
    descriptionEn: 'Awarded to early participants of the Legacy Pack 4.0 launch.',
    howToGet: '在 Pack 4.0 上线后的第一小时内至少开启 1 个卡包',
    howToGetEn: 'Open at least 1 pack within the first hour of Pack 4.0 launch',
    category: 'gacha',
    rarity: 'Uncommon',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-pack4',
  },
  {
    id: 'sbt-legacy4-flash',
    name: 'Legacy 4.0 闪卡',
    nameEn: 'Legacy 4.0 Flash Mint',
    description: '授予在 Legacy Pack 4.0 上线后一分钟内进入游戏的用户。',
    descriptionEn: 'Awarded to users who entered the game within the first minute of Legacy Pack 4.0 launch.',
    howToGet: '在 Legacy 4.0 上线后的第一分钟内购买礼包',
    howToGetEn: 'Purchase a pack within the first minute of Legacy 4.0 launch',
    category: 'gacha',
    rarity: 'Rare',
    available: false,
    holders: 0,
    imgUrl: '',
    relatedEventId: 'evt-pack4',
  },
  {
    id: 'sbt-superliquid-tester',
    name: 'SuperLiquid 测试者',
    nameEn: 'SuperLiquid Tester',
    description: '授予参与 2026年第一季度 Beta 2.0 期间 SuperLiquid 测试运行的用户。',
    descriptionEn: 'Awarded to users who participated in the SuperLiquid test run during Q1 2026 Beta 2.0.',
    howToGet: '参与 SuperLiquid 测试运行',
    howToGetEn: 'Participate in the SuperLiquid test run',
    category: 'special',
    rarity: 'Rare',
    available: true,
    holders: 0,
    imgUrl: '',
  },
  {
    id: 'sbt-affiliate',
    name: '联盟徽章',
    nameEn: 'Affiliate Badge',
    description: '授予加入 Renaiss 联盟计划的用户，属于 Beta 2.0 路线图更新的一部分。',
    descriptionEn: 'Awarded to users who join the Renaiss Affiliate Program, part of the Beta 2.0 roadmap update.',
    howToGet: '加入 Renaiss 联盟计划',
    howToGetEn: 'Join the Renaiss Affiliate Program',
    category: 'social',
    rarity: 'Common',
    available: true,
    holders: 0,
    imgUrl: '',
  },
];

const specialSbts = new Set(['sbt-vanguard', 'sbt-community-leader', 'sbt-ambassador', 'sbt-regional-ambassador']);

export const sbtCatalog: SbtCatalogItem[] = sbtItems.map(item => ({
  id: item.id,
  name: item.name,
  nameEn: item.nameEn,
  description: item.description,
  descriptionEn: item.descriptionEn,
  category: item.category,
  available: item.available,
  status: item.available ? '✅' as const : specialSbts.has(item.id) ? '⭕' as const : '❌' as const,
  holders: item.holders,
  availableLabel: item.available ? '✅' : specialSbts.has(item.id) ? '⭕' : '❌',
  howToGet: item.howToGet,
  howToGetEn: item.howToGetEn,
}));

// ─── Live Card Data (fetched from server API) ───
export const arbitrageCards: Card[] = [];
export const overpricedCards: Card[] = [];
